# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_sender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61ta_sender.proto\x12\x0c\x61i_economist\x1a\x1bgoogle/protobuf/empty.proto\"\x13\n\x04\x44\x61ta\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x17\n\x06Status\x12\r\n\x05state\x18\x01 \x01(\x05\x32\x86\x01\n\nDataSender\x12\x36\n\x08SendData\x12\x12.ai_economist.Data\x1a\x14.ai_economist.Status\"\x00\x12@\n\x10SendDataNoReturn\x12\x12.ai_economist.Data\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_DATA = DESCRIPTOR.message_types_by_name['Data']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'data_sender_pb2'
  # @@protoc_insertion_point(class_scope:ai_economist.Data)
  })
_sym_db.RegisterMessage(Data)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'data_sender_pb2'
  # @@protoc_insertion_point(class_scope:ai_economist.Status)
  })
_sym_db.RegisterMessage(Status)

_DATASENDER = DESCRIPTOR.services_by_name['DataSender']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATA._serialized_start=64
  _DATA._serialized_end=83
  _STATUS._serialized_start=85
  _STATUS._serialized_end=108
  _DATASENDER._serialized_start=111
  _DATASENDER._serialized_end=245
# @@protoc_insertion_point(module_scope)
