# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprotofile.proto\x12\x0bpackagename\"\"\n\x0cMessageInput\x12\x12\n\nmessage_in\x18\x01 \x01(\t\"$\n\rMessageOutput\x12\x13\n\x0bmessage_out\x18\x01 \x01(\t2R\n\x0bServiceName\x12\x43\n\x08SayHello\x12\x19.packagename.MessageInput\x1a\x1a.packagename.MessageOutput\"\x00\x62\x06proto3')



_MESSAGEINPUT = DESCRIPTOR.message_types_by_name['MessageInput']
_MESSAGEOUTPUT = DESCRIPTOR.message_types_by_name['MessageOutput']
MessageInput = _reflection.GeneratedProtocolMessageType('MessageInput', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEINPUT,
  '__module__' : 'protofile_pb2'
  # @@protoc_insertion_point(class_scope:packagename.MessageInput)
  })
_sym_db.RegisterMessage(MessageInput)

MessageOutput = _reflection.GeneratedProtocolMessageType('MessageOutput', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEOUTPUT,
  '__module__' : 'protofile_pb2'
  # @@protoc_insertion_point(class_scope:packagename.MessageOutput)
  })
_sym_db.RegisterMessage(MessageOutput)

_SERVICENAME = DESCRIPTOR.services_by_name['ServiceName']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEINPUT._serialized_start=32
  _MESSAGEINPUT._serialized_end=66
  _MESSAGEOUTPUT._serialized_start=68
  _MESSAGEOUTPUT._serialized_end=104
  _SERVICENAME._serialized_start=106
  _SERVICENAME._serialized_end=188
# @@protoc_insertion_point(module_scope)
